# -*- coding: utf-8 -*-
"""Ex7genai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHSIAedzXYOeYBs2BTxExwlfnOK-wVTC
"""

!apt-get install -y poppler-utils tesseract-ocr
!pip install -q faiss-cpu sentence-transformers PyPDF2 pdf2image pytesseract

from google.colab import files
uploaded = files.upload()

import re

# Remove code-like noise
clean_text = re.sub(r'[^a-zA-Z0-9.,?\n ]', ' ', text)

# Remove extra spaces
clean_text = re.sub(r'\s+', ' ', clean_text)

print("Clean text length:", len(clean_text))

import re

# Clean text
clean_text = re.sub(r'[^a-zA-Z0-9.,?\n ]', ' ', text)
clean_text = re.sub(r'\s+', ' ', clean_text)

# Split into sentences
sentences = clean_text.split('.')

chunks = []

for s in sentences:
    s = s.strip()

    # ❌ REMOVE BAD LINES
    if len(s) < 40:
        continue
    if "print" in s or "import" in s or "code" in s.lower():
        continue
    if "output" in s.lower():
        continue

    chunks.append(s)

print("Total clean chunks:", len(chunks))
print("\nSample:", chunks[:3])

from PyPDF2 import PdfReader
from pdf2image import convert_from_path
import pytesseract
import re

pdf_path = list(uploaded.keys())[0]

text = ""

# ===== TRY NORMAL PDF EXTRACTION =====
reader = PdfReader(pdf_path)
for page in reader.pages:
    if page.extract_text():
        text += page.extract_text()

# ===== IF FAILED → USE OCR =====
if len(text.strip()) < 50:
    print("Using OCR...")
    images = convert_from_path(pdf_path)
    for img in images:
        text += pytesseract.image_to_string(img)

print("Raw text length:", len(text))

# ===== CLEAN TEXT (REMOVE NOISE) =====
clean_text = re.sub(r'[^a-zA-Z0-9.,?\n ]', ' ', text)
clean_text = re.sub(r'\s+', ' ', clean_text)

print("Clean text length:", len(clean_text))

# ===== CHUNKING (GOOD QUALITY) =====
chunks = []

for i in range(0, len(clean_text), 800):
    chunk = clean_text[i:i+800]
    if len(chunk.strip()) > 200:
        chunks.append(chunk)

print("Total chunks:", len(chunks))

# Preview
print("\nSample chunk:\n", chunks[0][:300])

from sentence_transformers import SentenceTransformer
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(chunks)
embeddings = np.array(embeddings)

print("Embedding shape:", embeddings.shape)

import faiss

faiss.normalize_L2(embeddings)

dimension = embeddings.shape[1]
index = faiss.IndexFlatIP(dimension)
index.add(embeddings)

print("FAISS Ready!")

from transformers import AutoTokenizer, AutoModelForCausalLM

llm_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

llm_tokenizer = AutoTokenizer.from_pretrained(llm_name)
llm_model = AutoModelForCausalLM.from_pretrained(llm_name)

print("LLM Loaded!")

def ask_question(query, k=2):

    query_vec = model.encode([query])
    query_vec = np.array(query_vec)

    faiss.normalize_L2(query_vec)

    scores, indices = index.search(query_vec, k)

    context = ""
    for idx in indices[0]:
        context += chunks[idx][:400] + "\n"

    print("\n--- Retrieved Context ---\n")
    print(context)

    prompt = f"""
Answer the question using ONLY the context below.

Context:
{context}

Question: {query}
Answer:
"""

    inputs = llm_tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)

    output = llm_model.generate(**inputs, max_new_tokens=50)

    answer = llm_tokenizer.decode(output[0], skip_special_tokens=True)

    print("\n--- Final Answer ---\n")
    print(answer)


# 🔥 ASK HERE
ask_question("What is the aim of this experiment?")