# -*- coding: utf-8 -*-
"""Ex 6 Genai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BgOKkgr9CmI6lswDZIrxuLZtSvD6elmv
"""

# STEP 1: Install Libraries
!pip install faiss-cpu transformers torch pandas

# STEP 2: Upload Dataset
from google.colab import files
uploaded = files.upload()

# STEP 3: Load Dataset
import pandas as pd

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("Dataset Loaded Successfully")
print(df.head())

# STEP 4: Select Text Column
TEXT_COLUMN = df.columns[0]
item_texts = df[TEXT_COLUMN].astype(str).tolist()

print("Total items:", len(item_texts))
print("Sample item:", item_texts[0])

# STEP 5: Load Transformer Model
from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np
import faiss

device = "cuda" if torch.cuda.is_available() else "cpu"

model_name = "sentence-transformers/all-MiniLM-L6-v2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name).to(device)
model.eval()

# STEP 6: Encode Texts into Embeddings
def encode_texts(texts, batch_size=32):
    all_embeddings = []

    with torch.no_grad():
        for i in range(0, len(texts), batch_size):
            batch = texts[i:i+batch_size]

            tokens = tokenizer(
                batch,
                padding=True,
                truncation=True,
                return_tensors="pt"
            ).to(device)

            outputs = model(**tokens)

            embeddings = outputs.last_hidden_state.mean(dim=1)
            embeddings = embeddings.cpu().numpy().astype("float32")

            all_embeddings.append(embeddings)

    return np.vstack(all_embeddings)

item_embeddings = encode_texts(item_texts)

# STEP 7: Normalize Embeddings
faiss.normalize_L2(item_embeddings)

print("Embeddings shape:", item_embeddings.shape)

# STEP 8: Build FAISS Index
embedding_dim = item_embeddings.shape[1]
index = faiss.IndexFlatIP(embedding_dim)

index.add(item_embeddings)

print("FAISS index built with", index.ntotal, "items")

# STEP 9: Similarity Search Function
def get_similar_items(item_id, k=5):
    query_vector = item_embeddings[item_id:item_id+1]

    scores, indices = index.search(query_vector, k)

    return scores[0], indices[0]

# STEP 10: Test Similarity Retrieval
query_id = 0

scores, idxs = get_similar_items(query_id, k=5)

print("\nQUERY ITEM:")
print(item_texts[query_id])

print("\nSIMILAR ITEMS:")
for score, idx in zip(scores, idxs):
    print(f"-> {item_texts[idx]} (score={score:.3f})")