# -*- coding: utf-8 -*-
"""EX 8 GENAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TaZsmhLJzP1gB2aCqOM3-1x0qdXzd2BV
"""

!pip install transformers gradio evaluate sentencepiece sacrebleu

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/mt5-small"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def generate_response(question):
    inputs = tokenizer("question: " + question, return_tensors="pt")
    outputs = model.generate(**inputs, max_new_tokens=50)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

import gradio as gr

def chatbot(query):
    return generate_response(query)

interface = gr.Interface(
    fn=chatbot,
    inputs="text",
    outputs="text",
    title="Customer Support Chatbot"
)

interface.launch(share=True)

!pip install rouge_score

!pip install transformers evaluate rouge_score sacrebleu sentencepiece

from evaluate import load

rouge = load("rouge")
bleu = load("bleu")

# Example test data
predictions = []
references = []

test_questions = [
    "What is a bank?",
    "What is a debit card?"
]

actual_answers = [
    "A bank is a financial institution that manages money.",
    "A debit card allows direct access to your bank account."
]

for q in test_questions:
    pred = generate_response(q)
    predictions.append(pred)

references = actual_answers

# Compute scores
rouge_score = rouge.compute(predictions=predictions, references=references)
bleu_score = bleu.compute(predictions=predictions, references=references)

print("ROUGE-L:", rouge_score["rougeL"])
print("BLEU:", bleu_score["bleu"])